:arrivals:
  - :queue_id: :q1
    :time: 2.5

:queues:
  - :id: :q1
    :servers: 1
    :capacity: 3
    :min_arrival: 3
    :max_arrival: 7
    :min_service: 9
    :max_service: 15

:seed: 10

:duration: 300
